export const biddingData = [
    {
        quoteid:"ATSPL-BPL-123",
        location:"Delhi",
        request_by:"Abc Compnay",
        service:"Material Procurement",
        material:"Fly Ash",
        added_date: '01 Aug 2022',
        quantity: '157 MT',
        status: 'Open',
    },
    {
        quoteid:"ATSPL-MUM-223",
        location:"Mumbai",
        request_by:"Xyz Compnay",
        service:"Material Procurement",
        material:"Cement",
        added_date: '03 Aug 2022',
        quantity: "446 pkt",
        status: true,
    },
    {
        quoteid:"ATSPL-DLH-11",
        location:"Delhi",
        request_by:"ABC Supplier",
        service:"Transport Request",
        material:"Fly Ash",
        added_date: '10 Aug 2012',
        quantity: "376 Ton",
        status: true,
    },
    {
        quoteid:"ATSPL-BPL-3",
        location:"Pune",
        request_by:"Abc Constraction",
        service:"Transport Request",
        material:"Cement",
        added_date: '12 Aug 2012',
        quantity: 56,
        status: false,
    },
    {
        quoteid:"ATSPL-SRT-123",
        location:"Surat",
        request_by:"New Gujarat Suppliers",
        service:"Transaport",
        material:"Fly Ash",
        added_date: "24 Aug 2022",
        quantity: 337,
        status: false,
    },
    {
        quoteid:"ATSPL-BPL-123",
        location:"Gurgaon",
        request_by:"Abc Compnay",
        service:"Material Procurement",
        material:"Fly Ash",
        added_date: '09 Aug 2022',
        quantity: 482,
        status: true,
    },
]