export const tb_bookingData = [
    {
        pono:"ATSPL-BPL-123",
        pickup:"Hyderabad",
        drop:"Pune",
        customer:"New Rakesh Wholesaler",
        booking_type:"RFQ",
        material:"Fly Ash",
        po_date: '01 Aug 2022',
        quantity: '157 MT',
        status: false,
    },
    {
        pono:"ATSPL-MUM-223",
        pickup:"Mumbai",
        drop:"Shirdi",
        customer:"PWDF Compnay",
        booking_type:"Direct",
        material:"Cement",
        po_date: '03 Aug 2022',
        quantity: "446 pkt",
        document:"",
        status: true,
    },
    {
        pono:"ATSPL-DLH-11",
        pickup:"Delhi",
        drop:"Agra",
        customer:"New Sharma Supplier",
        booking_type:"RFQ",
        material:"Fly Ash",
        po_date: '10 Aug 2012',
        quantity: "376 Ton",
        status: true,
    },
    {
        pono:"ATSPL-BPL-3",
        pickup:"Hyderabad",
        drop:"Bengaluru",
        customer:"Vinayak Constraction",
        booking_type:"RFQ",
        material:"Cement",
        po_date: '12 Aug 2012',
        quantity: 56,
        status: false,
    },
    {
        pono:"ATSPL-SRT-123",
        pickup:"Surat",
        drop:"Mumbai",
        customer:"New Gujarat Suppliers",
        booking_type:"RFQ",
        material:"Fly Ash",
        po_date: "24 Aug 2022",
        quantity: 337,
        status: false,
    },
    {
        pono:"ATSPL-BPL-123",
        pickup:"Bengaluru",
        drop:"Pune",
        customer:"Sinha Supplier PVT LTD",
        booking_type:"Direct",
        material:"Fly Ash",
        po_date: '09 Aug 2022',
        quantity: 482,
        status: true,
    }

]