export const invoiceData = [
    {
        invoiceno:"INVC123",
        pono:"ATSPL-BPL-123",
        location:"Hyderabad",
        request_by:"Abc Compnay",
        service:"Procurement",
        material:"Fly Ash",
        invoice_date: '01 Aug 2022',
        deliverd_on: '20 July 2022',
        amount: 1200,
        status: false,
    },
    {
        invoiceno:"INVC112",
        pono:"ATSPL-MUM-223",
        location:"Mumbai",
        request_by:"Xyz Compnay",
        service:"Procurement",
        material:"Cement",
        invoice_date: '03 Aug 2022',
        deliverd_on: '02 Aug 2022',
        amount: 1200,
        document:"",
        status: true,
    },
    {
        invoiceno:"INVC121",
        pono:"ATSPL-DLH-11",
        location:"Delhi",
        request_by:"ABC Supplier",
        service:"Transport",
        material:"Fly Ash",
        invoice_date: '10 Aug 2012',
        deliverd_on: '02 Aug 2022',
        amount: 1200,
        status: true,
    },
    {
        invoiceno:"INVC111",
        pono:"ATSPL-BPL-3",
        location:"Hyderabad",
        request_by:"Abc Constraction",
        service:"Transport",
        material:"Cement",
        invoice_date: '12 Aug 2012',
        deliverd_on: '10 Aug 2022',
        amount: 56,
        status: false,
    },
    {
        invoiceno:"INVC011",
        pono:"ATSPL-SRT-123",
        location:"Surat",
        request_by:"New Gujarat Suppliers",
        service:"Transaport",
        material:"Fly Ash",
        invoice_date: "24 Aug 2022",
        deliverd_on: '20 Aug 2022',
        amount: 337,
        status: false,
    },
    {
        invoiceno:"INVC01234",
        pono:"ATSPL-BPL-123",
        location:"ATSPL-BPL-123",
        request_by:"Abc Compnay",
        service:"Procurement",
        material:"Fly Ash",
        invoice_date: '09 Aug 2022',
        deliverd_on: '05 Aug 2022',
        amount: 482,
        status: true,
    },
]