export const ordersData = [
    {
        pono:"ATSPL-BPL-123",
        location:"Hyderabad",
        request_by:"Abc Compnay",
        service:"Procurement",
        material:"Fly Ash",
        added_date: '01 Aug 2022',
        quantity: '157 MT',
        status: false,
    },
    {
        pono:"ATSPL-MUM-223",
        location:"Mumbai",
        request_by:"Xyz Compnay",
        service:"Procurement",
        material:"Cement",
        added_date: '03 Aug 2022',
        quantity: "446 pkt",
        document:"",
        status: true,
    },
    {
        pono:"ATSPL-DLH-11",
        location:"Delhi",
        request_by:"ABC Supplier",
        service:"Transport",
        material:"Fly Ash",
        added_date: '10 Aug 2012',
        quantity: "376 Ton",
        status: true,
    },
    {
        pono:"ATSPL-BPL-3",
        location:"Hyderabad",
        request_by:"Abc Constraction",
        service:"Transport",
        material:"Cement",
        added_date: '12 Aug 2012',
        quantity: 56,
        status: false,
    },
    {
        pono:"ATSPL-SRT-123",
        location:"Surat",
        request_by:"New Gujarat Suppliers",
        service:"Transaport",
        material:"Fly Ash",
        added_date: "24 Aug 2022",
        quantity: 337,
        status: false,
    },
    {
        pono:"ATSPL-BPL-123",
        location:"ATSPL-BPL-123",
        request_by:"Abc Compnay",
        service:"Procurement",
        material:"Fly Ash",
        added_date: '09 Aug 2022',
        quantity: 482,
        status: true,
    }
]