export const userdata = [
        {
            id: 1,
            name: 'Mayur',
            email: "mayur@gmail.com",
            mobile: "7989787777",
            type: 'Admin',
            status: true,
            added_on: "10/20/2022",
        },
        {
            id: 2,
            name: 'Kundan',
            email: "kundan@gmail.com",
            mobile: "7989787777",
            type: 'Admin',
            status: true,
            added_on: "10/20/2022",
        },
        {
            id: 3,
            name: 'Sonali',
            email: "sonali@gmail.com",
            mobile: "7989787777",
            type: 'Admin',
            status: true,
            added_on: "10/20/2022",
        },
        {
            id: 4,
            name: 'Shubham',
            email: "shubham@gmail.com",
            mobile: "7989787777",
            type: 'Site Admin',
            status: false,
            added_on: "10/20/2022",
        },
]